Loaded module: cuda/12.4
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: viswacolab (viswacolab-technical-university-of-denmark) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /zhome/d5/3/214816/viswa/wandb/run-20250419_100208-propw6du
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lucky-plasma-118
wandb: ‚≠êÔ∏è View project at https://wandb.ai/viswacolab-technical-university-of-denmark/maddpg_mrr
wandb: üöÄ View run at https://wandb.ai/viswacolab-technical-university-of-denmark/maddpg_mrr/runs/propw6du
Traceback (most recent call last):
  File "/zhome/d5/3/214816/viswa/rl_mrr_all_gru_ddqn_copy.py", line 564, in <module>
    loss, mean_q = agent.learn(global_n_steps)
  File "/zhome/d5/3/214816/viswa/gru_ddqn.py", line 143, in learn
    states = T.tensor(state, dtype=T.float).to(self.q_eval.device)
KeyboardInterrupt
Traceback (most recent call last):
  File "/zhome/d5/3/214816/viswa/rl_mrr_all_gru_ddqn_copy.py", line 564, in <module>
    loss, mean_q = agent.learn(global_n_steps)
  File "/zhome/d5/3/214816/viswa/gru_ddqn.py", line 143, in learn
    states = T.tensor(state, dtype=T.float).to(self.q_eval.device)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/zhome/d5/3/214816/viswa/my_env/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/zhome/d5/3/214816/viswa/my_env/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
